CREATE TABLE Bidder (
  UserID VARCHAR(80) NOT NULL,
  Rating INTEGER NOT NULL,
  Location VARCHAR(80) DEFAULT NULL,
  Country VARCHAR(80) DEFAULT NULL,

  PRIMARY KEY (UserID)
);

CREATE TABLE Seller (
  UserID VARCHAR(80) NOT NULL,
  Rating INTEGER NOT NULL,

  PRIMARY KEY (UserID)
);


CREATE TABLE Bid (
  ItemID INTEGER NOT NULL,
  UserID VARCHAR(80) NOT NULL,
  Time TIMESTAMP NOT NULL,
  Amount DECIMAL(8, 2) NOT NULL,

  PRIMARY KEY (ItemID, UserID, Time)
);

CREATE TABLE Item (
  ItemID INTEGER NOT NULL,
  Name VARCHAR(80) NOT NULL,
  Currently DECIMAL(8, 2) NOT NULL,
  Buy_Price DECIMAL(8, 2) DEFAULT NULL,
  First_Bid DECIMAL(8, 2) NOT NULL,
  Number_of_Bids INTEGER NOT NULL,
  Location VARCHAR(80) NOT NULL,
  Latitude VARCHAR(100) DEFAULT NULL,
  Longitude VARCHAR(100) DEFAULT NULL,
  Country VARCHAR(80) NOT NULL,
  Started TIMESTAMP NOT NULL,
  Ends TIMESTAMP NOT NULL,
  SellerID VARCHAR(80) NOT NULL,
  Description VARCHAR(4000) NOT NULL,

  PRIMARY KEY (ItemID),
  FOREIGN KEY (SellerID) REFERENCES Seller(UserID)
);


CREATE TABLE ItemCategory (
  ItemID INTEGER NOT NULL,
  Category VARCHAR(80) NOT NULL,

  PRIMARY KEY (ItemID, Category),
  FOREIGN KEY (ItemID) REFERENCES Item(ItemID) 
);

